# Generated by Django 4.2 on 2024-02-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                ("internal_ID", models.AutoField(primary_key=True, serialize=False)),
                ("external_ID", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("category", models.CharField(max_length=255)),
                ("avg_rating", models.FloatField()),
            ],
        ),
    ]
